// frontend-onesdk-sample-angular-vite/src/app/idverse/idverse.component.ts
import { Component, OnInit } from '@angular/core';
import { OnesdkTokenService } from '../onesdk-token.service';
import OneSDK from '@frankieone/one-sdk';
import { environment } from '../../environments/environment';

@Component({
	selector: 'app-idverse',
	standalone: true,
	imports: [],
	templateUrl: './idverse.component.html',
	styleUrl: './idverse.component.css'
})
export class IdverseComponent implements OnInit {
	constructor(private tokenService: OnesdkTokenService) { }

	async ngOnInit() {
		const oneSdk = await OneSDK({
			session: await this.tokenService.getToken(
				environment.CUSTOMER_ID2,
				environment.API_KEY2,
				environment.CUSTOMER_CHILD_ID2
			),
			recipe: {
				idv: {
					provider: {
						name: "ocrlabs"
					}
				}
			},
		});

		const flow = oneSdk.flow as unknown as (arg0: any) => any;

		// 4. Use IDV component
		const idv = flow("idv");
		const oneSdkIndividual = oneSdk.individual();
		oneSdkIndividual.addConsent("general");
		oneSdkIndividual.addConsent("docs");
		oneSdkIndividual.addConsent("creditheader");
		await oneSdkIndividual.submit();

		idv.mount("#idverse");
	}
}

// frontend-onesdk-sample-vue-vite/src/components/onesdk-test/IDVerse.vue
<script setup>
import { useOneSdkSessionWithChildId } from '@/composables/onesdk-session';
import OneSDK from '@frankieone/one-sdk';
import { watchEffect } from 'vue';

const session = useOneSdkSessionWithChildId()

watchEffect(async () => {
	if (!session.value) return

	const oneSdk = await OneSDK({
		session: session.value,
		mode: "development",
		recipe: {
			idv: {
				provider: {
					name: "ocrlabs"
				}
			}
		},
	});

		const idv = oneSdk.flow("idv");
		const oneSdkIndividual = oneSdk.individual();
		oneSdkIndividual.addConsent("general");
		oneSdkIndividual.addConsent("docs");
		oneSdkIndividual.addConsent("creditheader");
		await oneSdkIndividual.submit();

		idv.mount("#idverse");
})
</script>

<template>
	<div id="idverse" style="width: '100%'; height: 85vh"></div>
</template>
